### ISSUE TITLE
Make Sure Each Person Cycles Evenly Through Each Group Number

### ISSUE THREAD

**Issue by thomastthai** [islemaster/good-enough-golfers#16]
Let's say we have a class of 20 students divided into four groups (0, 1, 2, 3) with five students per group. Each group is assigned specific tasks, and we want our students to get a chance to be a part of each group so they can perform each task at least once per round. We want the constraints of minimizing two students being together in any group, and each student rotating through each group number before repeating.

Example:

Student S1 has to rotate through groups G1, G2, G3, or G4 before revisiting a group they already were a part of. The order of which group they visit first won't matter to help with grouping with other students.

I've thought about two ways to handle this. The first is to use another 2-dimensional array with the students on the X-axis and the group numbers on the Y-axis. The logic used currently for finding permutations of players and pairing players (students) by weight could be reused. Then combine the weights of student X group and student X student to find the ones with the lowest weights. The second way is to use a 3-dimensional array: students x students x groups. I've not flushed out how to handle the 3-dimension array. 

Would love to hear other ideas on how to make this work.

**Comment by islemaster** [comment]
I consider this out of scope as well, even though it is a neat idea. I think you've described a fundamentally different (and maybe unsolvable) combinatorics problem.

Consider: Twelve students visit four workstations for (necessarily) four rounds, so that each student visits each workstation once.
```
Round 1
ABC   DEF   GHI   JKL

In round two each group _must_ distribute across the three workstations they have not visited:
DGJ   AHK   BEL   CFI

By round three each original group from group one must *rotate* remaining stations or violate a constraint.
Here's one of two zero-conflict possibilities for the first group's round three. Try placing another!
...   C..   A..   B..
```

It's come up a few times in feedback that people want this: A way to ensure players encounter every group number or encounter every other student at least once. But the "maximize distinct encounters" problem is fundamentally different from the "minimize repeat encounters" problem that Good Enough Golfers is based on. If we're just approximating each they could probably both use the genetic approach I'm using here, but when you try to solve them together the goals eventually come into conflict, and we have to decide: What are the relative weights of the two constraints? And how comfortable are we with approximations?

If "minimize repeat group visits" is good enough for your use case, the [new "Use Group Leaders" feature](https://github.com/islemaster/good-enough-golfers/commit/be39e4f63f5ecc7474143eb749691ccccf5f6638) could get you close to something like this. It locks the first "player" in each group to that group number, which then gets considered when subsequently placing players - so the system tries not to put any player with the same group leader multiple times (weighed the same as repeat encounters with other players). This could work well for a scenario where you had twelve stations but only four rounds, and just wanted to make sure students didn't visit the same station twice. But it won't solve the "tour of every station" problem for every student.
